server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
