### 돈 뿌리기
POST http://{{host}}:{{port}}/api/sharing
Content-Type: application/json
X-USER-ID: 123
X-ROOM-ID: 321

{
  "amount": 10000,
  "numberOfTarget": 3
}

### 가져가기 1
PUT http://{{host}}:{{port}}/api/sharing/{{token}}
Content-Type: application/json
X-USER-ID: 1
X-ROOM-ID: 321

### 가져가기 2
PUT http://{{host}}:{{port}}/api/sharing/{{token}}
Content-Type: application/json
X-USER-ID: 2
X-ROOM-ID: 321

###가져가기 3
PUT http://{{host}}:{{port}}/api/sharing/{{token}}
Content-Type: application/json
X-USER-ID: 3
X-ROOM-ID: 321

### 토큰 조회
GET http://{{host}}:{{port}}/api/sharing/{{token}}
Accept: application/json
X-USER-ID: 123
X-ROOM-ID: 321
